### PR TITLE
Added Background Image and hover effect 

### LINKED ISSUE #370: Change the background of Why choose us section
Share the background suggestions here.

### PR DESCRIPTION
**Pull request by gkm0001**
## Summary
 Update background Image and provide hover effect  .

## Type of change
_Please select the relevant option._

-  [ ] Bug fix 
-  [ ] New feature
-  [x] Breaking change
-  [ ]Documentation update
-  [ ] Other (please describe)

## Checklist
_Please tick the relevant options._
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Screenshots
 
 
AISKCON-Construction (1)

### CODE REVIEW

**Comment by gkm0001** [comment]
also added hover effect .

**Comment by kartikayasija** [comment]
share screenshots or rec

**Comment by gkm0001** [comment]
https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/121250607/d64a48ce-04d5-4695-9fca-e2ff3129ebe3

Added background image choose by you and added hover affect .

**Comment by kartikayasija** [comment]
Give ``` background: rgba(0, 0, 0,0.5); ```  and  ``` background: rgba(0, 0, 0,0.7); ``` in hover

**Comment by gkm0001** [comment]
DONE

**Pull request merged**
