### PR TITLE
hover effect added

### PR DESCRIPTION
**Pull request by akankshachanana1**
I added a hover effect to every button so that it grows in size when it is hovered over.

## Type of change

- [ ] New feature

## Checklist
_Please tick the relevant options._
- [ ] My code follows the code style of this project.
- [ ] My changes are in accordance with the UI of the project

### CODE REVIEW

**Comment by akankshachanana1** [comment]
Before

Screenshot 2023-05-25 192452

**Comment by akankshachanana1** [comment]
Now
I have increased the size of button Hover

Screenshot 2023-05-25 192532

**Comment by akankshachanana1** [comment]
Now 
I have Increased the size of button on hover
Screenshot 2023-05-25 192901

**Comment by kartikayasija** [comment]
Hello @akankshachanana1 , this scale effect is not looking good on buttons.
Add this hover effects on all buttons, Also don't directly add css to button attribute.

https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/115306535/4ef93841-bc9f-4dcb-840b-a45872b6a3e1

**Comment by akankshachanana1** [comment]
Ok sir I will work on it

**Comment by akankshachanana1** [comment]
Gradient effect added

https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/127978268/8e868ed0-2f6e-47c6-9a81-9f0d744800c4

**Comment by kartikayasija** [comment]
Resolve conflicts

**Pull request closed without merging**
