### PR TITLE
Added close button to the chatbot

### PR DESCRIPTION
**Pull request by VyjayantiN**
## Summary
Added close button to the chatbot
This pull request adds a close button to the chatbot, allowing users to close the chatbot window when pressed. The close button provides a more intuitive way for users to exit the chatbot interface.

## Fixes # (issue)
Fixed the issue of the chatbot not having a close button

## Type of change
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change
- [ ] Documentation update
- [ ] Other (please describe)

## Checklist
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## Screenshots
image

### CODE REVIEW

**Comment by VyjayantiN** [comment]
@Neilblaze  @AbhiPatel10  Please look into it

**Comment by VyjayantiN** [comment]
Thanks @Neilblaze !! But could you please add the tag - GSSOC'23 for this issue!! I am a GSSOC'23 contributor.

**Comment by Neilblaze** [comment]
@VyjayantiN It's currently under review. Once it's approved, I'll add that label don't worry!

**Comment by kartikayasija** [comment]
@VyjayantiN Make the close button more attractive.

**Comment by VyjayantiN** [comment]
@kartikayasija How is this?
image

**Comment by VyjayantiN** [comment]
@kartikayasija could you please add the tag - GSSOC'23 for this issue!!

**Comment by kartikayasija** [comment]
I think second or third one would be good. What say?

**Comment by VyjayantiN** [comment]
Yes anything is okay for me. I think third one is decent. @kartikayasija

**Comment by kartikayasija** [comment]
Go fir it @VyjayantiN

**Comment by VyjayantiN** [comment]
Done @kartikayasija!! Please add labels and check the PR!!

**Comment by kartikayasija** [comment]
After the chatbot is closed, it is not opening again. Solve this.
There should be animation when it closes.
Also vertically align this close button in center.



https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/115306535/8ca8cc5b-d30e-4a00-95df-503d643abe32

**Comment by VyjayantiN** [comment]
@Neilblaze @kartikayasija Please check this out. I made this two days ago.  Also , do please add the GSSOC'23 label.

**Comment by Neilblaze** [comment]
@VyjayantiN I see that you have a [pending review](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/pull/348#issuecomment-1586273610). Awaiting @kartikayasija's response.

**Comment by VyjayantiN** [comment]
@kartikayasija I will check that out. Give me some time.

**Comment by kartikayasija** [comment]
@VyjayantiN Are you working on it?

**Comment by VyjayantiN** [comment]
@kartikayasija Yes

**Comment by VyjayantiN** [comment]
@kartikayasija I finished. Please check that out!!

**Comment by VyjayantiN** [comment]
@kartikayasija Please look into it.

**Pull request closed without merging**
