### PR TITLE
Fix: Add favicon to all pages

### PR DESCRIPTION
**Pull request by DrVickie8**
## Summary
_Provide an overview of the change. List any dependencies that are required for this change._
Added favicon to all the pages

## Type of change
_Please select the relevant option._
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation update
- [Add favicon] Other (please describe)

## Checklist
_Please tick the relevant options._
- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ x] All new and existing tests passed.

## Screenshots
_Provide screenshots to help explain your changes._
Pages with favicon

Pages without favicon

## Additional context
_Add any other context about the pull request here._

### CODE REVIEW

**Comment by kartikayasija** [comment]
Add screenshots in your PR

**Comment by DrVickie8** [comment]
@kartikayasija, sure will do.

**Comment by DrVickie8** [comment]
@kartikayasija I just added the screenshots, thanks.

**Comment by kartikayasija** [comment]
@DrVickie8 Great, Just resolve the conflicts.

**Comment by DrVickie8** [comment]
@kartikayasija I just resolved the conflict.

**Comment by DrVickie8** [comment]
Thank you so much! @kartikayasija

**Pull request merged**
