### PR TITLE
Navbar

### PR DESCRIPTION
**Pull request by saiful64**
## Summary
_Provide an overview of the change. List any dependencies that are required for this change._

## Type of change
_Please select the relevant option._
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change
- [x] Documentation update
- [ ] Other (please describe)

## Checklist
_Please tick the relevant options._
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Screenshots
_Provide screenshots to help explain your changes._

## Additional context
_Add any other context about the pull request here._

### CODE REVIEW

**Comment by AbhiPatel10** [comment]
Before making PR Please Create an Issue

Resolve conflict

**Comment by AbhiPatel10** [comment]
Make Different PR for different purpose like make new pr for readme file change

**Comment by saiful64** [comment]
can you please reopen it

**Comment by saiful64** [comment]
Also i found out now that clicking on navbar elements its not redirecting to the page

**Comment by saiful64** [comment]
Can you please reopen it i have done it need to PR otherwise like #136 you guys will assign it to someone else altough it was assigned to me by abhi patel.. Under GSSoC

**Pull request closed without merging**
