### PR TITLE
Get in Touch section

### LINKED ISSUE #25: Get in Touch Section

### PR DESCRIPTION
**Pull request by kartikayasija**
closes #25 
Icon position fixed
Previous PR was closed by mistake.
image

### CODE REVIEW

**Comment by AbhiPatel10** [comment]
Why you close the PR Just Work on one PR only.

**Comment by AbhiPatel10** [comment]
Increase font size and add some dummy data in blank boxes

**Comment by kartikayasija** [comment]
@AbhiPatel10  

- Font Size increased

- Dummy Data Added

image

**Comment by AbhiPatel10** [comment]
Use only one color for card----> Use This  #1C55A4

Still increase font size for heading and paragraph tooo

**Comment by kartikayasija** [comment]
Background Color changed to #1C55A4
Font Size increased
image

**Comment by AbhiPatel10** [comment]
Looks awesome, Appreciate your work @kartikayasija

**Pull request merged**
