### PR TITLE
Added a Slider to Repairs

### LINKED ISSUE #215: [GSSOC'23] Add Slider To Website
I want to add slider to each repairs and services that better describes the examples stated such as in the case of Home Repairs a slider images of walls, roofs, plumbing, electrical systems. So even a customer does not read the text he/she will grasp the idea of what the repair or service looks like.

@kartikayasija if you see this as a good issue I would like to work on it as a contribution for GSSOC'23.

### PR DESCRIPTION
**Pull request by roberanegussie**
## Summary
_Provide an overview of the change. List any dependencies that are required for this change._
I have added an image slider to each kind of repair found on that page. I have added images generated by Bing to bring more attention to the images.  

## Type of change
_Please select the relevant option._
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change
- [ ] Documentation update
- [ ] Other (please describe)

## Checklist
_Please tick the relevant options._
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Screenshots
_Provide screenshots to help explain your changes._
image
image
image

## Additional context
_Add any other context about the pull request here._

### CODE REVIEW

**Comment by kartikayasija** [comment]
Remove Scroll, reduce box shadow and use professional images.
Don't use cartoon images, they are looking good but this is a professional project.

**Comment by roberanegussie** [comment]
> Remove Scroll, reduce box shadow, add border radius and use professional images. Don't use cartoon images, they are looking good but this is a professional project.

Okay I will correct the PR based on your feedback.

**Comment by roberanegussie** [comment]
@kartikayasija I have updated the PR based on your feedback. Please review.
image
image
image
image

**Comment by kartikayasija** [comment]
Images are not looking good, use vectors like the previous ones, and What is this blue border?

**Comment by roberanegussie** [comment]
Updated the PR please review.

image
image
image

**Comment by roberanegussie** [comment]
I see there are 5 conflicts but if I use one id for all all images it will only change the carousel of the first images. If there is another way I can resolve the conflicts please let me know.

**Pull request closed without merging**
