### PR TITLE
Readme is updated

### PR DESCRIPTION
**Pull request by shraddha761**
## Summary
_Provide an overview of the change. List any dependencies that are required for this change._
Issue reference - #160 
## Type of change
_Please select the relevant option._
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change
- [x] Documentation update
- [ ] Other (please describe)

## Checklist
_Please tick the relevant options._
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## Screenshots
_Provide screenshots to help explain your changes._
image

## Additional context
_Add any other context about the pull request here._
Readme is updated with please suggest the changes if any.
Request to increase the level as I try my best to make readme attractive

### CODE REVIEW

**Comment by kartikayasija** [comment]
@shraddha761 Add names of Project Admin, Maintainers in the readme.

**Comment by shraddha761** [comment]
> @shraddha761 Add names of Project Admin, Maintainers in the readme.

I add the name of admin and mentor is their more maintainer please let me know

**Comment by kartikayasija** [comment]
Share screenshot

**Comment by shraddha761** [comment]
> > @shraddha761 Add names of Project Admin, Maintainers in the readme.
> 
> I add the name of admin and mentor is their more maintainer please let me know



> Share screenshot

image

**Comment by kartikayasija** [comment]
add Rolika Agarwal, Kartikay Asija in Mentors

**Comment by shraddha761** [comment]
@kartikayasija please have a look i made the proposed changes

**Pull request merged**
