### PR TITLE
new bg img for services

### PR DESCRIPTION
**Pull request by kanikakaur27**
#127 
new bg img for services which matches the theme of the bg of repairs as well

## Summary
New bg img for services. Added a new img 'services.jpeg' for the same.

## Type of change
_Please select the relevant option._
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation update
- [x] Other - change in UI

## Checklist
_Please tick the relevant options._
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Screenshots
Screenshot 2023-05-24 at 9 31 01 PM

## Additional context
_Add any other context about the pull request here._

### CODE REVIEW

**Comment by kartikayasija** [comment]
@kanikakaur27 The text is not clearly visible due to white color of background, Try something else.

**Comment by kanikakaur27** [comment]
HI @kartikayasija should I try a different font colour or would you prefer a different background image?

**Comment by kartikayasija** [comment]
> Hi @kartikayasija do i create a new pull request?

No need, just share screenshot of your change.

**Comment by kanikakaur27** [comment]
Sure. Let me know incase you want any other change. 

Screenshot 2023-05-25 at 9 36 37 PM

**Pull request merged**
