### PR TITLE
Safety part added

### PR DESCRIPTION
**Pull request by rayarka26**
Issue Number #260
Please assign Girlscript Summer of Code 2023 label

## Summary
_Provide an overview of the change. List any dependencies that are required for this change._

## Type of change
_Please select the relevant option._
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change
- [ ] Documentation update
- [ ] Other (please describe)

## Checklist
_Please tick the relevant options._
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Screenshots
_Provide screenshots to help explain your changes._

## Additional context
_Add any other context about the pull request here._

### CODE REVIEW

**Comment by rayarka26** [comment]
I have added it under the About section
Screenshot (59)

**Comment by rayarka26** [comment]
#gssoc23

**Comment by piyushlakheda** [comment]
LGTM

**Comment by kartikayasija** [comment]
@rayarka26 Do the following changes 👍 

- Use a high quality Vector img
image

- Remove these bullets and don't change the Navbar
image

- Reduce bullet points (5-6) and increase line-height a little bit.
image

**Comment by rayarka26** [comment]
Screenshot (65)

**Comment by rayarka26** [comment]
Please include the GSSOC'23 Label
You missed in the issue

**Comment by kartikayasija** [comment]
image


add a class and do the change in that Don't change the paragraph attribute directly

**Comment by rayarka26** [comment]
Sorry i wrongly changed it.
I've corrected

**Pull request merged**
