### PR TITLE
modified service section

### PR DESCRIPTION
**Pull request by dgarg6333**
FIXES#430
old
Screenshot 2023-06-25 100057

new
Screenshot 2023-06-25 121331
@kartikayasija @Neilblaze please merge my pull request #435

### CODE REVIEW

**Review by Neilblaze — APPROVED** [review]
/cc: @kartikayasija thoughts?

**Comment by kartikayasija** [comment]
Also align it vertically.

**Comment by dgarg6333** [comment]
@kartikayasija @Neilblaze i have align it vertically , please merge my pull request #435

**Comment by Neilblaze** [comment]
LGTM, waiting for @kartikayasija's approval.

**Review by kartikayasija — APPROVED** [review]

**Pull request merged**
