### PR TITLE
Fixed the issue of missing image in the home screen 

### PR DESCRIPTION
**Pull request by VyjayantiN**
##Summary
This pull request addresses the issue of a missing image in the container-expert section and the display of alternate text instead.

## Fixes # (issue)
I have fixed the missing image issue in the container-expert section by adding the missing picture.

## Type of change
_Please select the relevant option._
- [x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation update
- [ ] Other (please describe)

## Checklist
_Please tick the relevant options._
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Screenshots
image

### CODE REVIEW

**Comment by VyjayantiN** [comment]
@Neilblaze @kartikayasija Please look into it when possible!!

**Comment by kartikayasija** [comment]
@VyjayantiN Also change this img in Contact us page.
image

**Comment by VyjayantiN** [comment]
Ok @kartikayasija

**Comment by VyjayantiN** [comment]
I added image to the contact page as well!! Please check out this screenshot!!
image

**Pull request merged**
