### PR TITLE
Update contribution.md DOC

### LINKED ISSUE #365: Update contribution.md DOC
I want to update contribution.md DOC and make it more readable by adding some meaningful content, git commands and Step-by-Step guide for contribution

### PR DESCRIPTION
**Pull request by silky-modi22**
## Summary
_Provide an overview of the change. List any dependencies that are required for this change._

## Type of change

Documentation update

## Checklist
 I have updated the documentation accordingly.

## Screenshots
image
image

Please merge my PR under GSSOC 2023

### CODE REVIEW

**Comment by kartikayasija** [comment]
@silky-modi22 This issue is already assigned to someone else, Please get the issue assigned first and then only raise the PR.

**Comment by silky-modi22** [comment]
Can you please assign this issue to me i want to work on it

**Comment by kartikayasija** [comment]
@silky-modi22 I would be happy to assign you but someone already has raised the PR for the same. Try to find some other issue or you can discuss any new feature you want to implement.

**Comment by silky-modi22** [comment]
Ok, thank you.

**Pull request closed without merging**
