### PR TITLE
headingadded'

### PR DESCRIPTION
**Pull request by karantec**
## Summary
_Provide an overview of the change. List any dependencies that are required for this change._

## Type of change
_Please select the relevant option._
- [x] Bug fix
- [x] New feature
- [ ] Breaking change
- [x] Documentation update
- [ ] Other (please describe)

## Checklist
_Please tick the relevant options._
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## Screenshots
_Provide screenshots to help explain your changes._

## Additional context
_Add any other context about the pull request here._

### CODE REVIEW

**Comment by karananu** [comment]
Changes has been done

**Comment by karananu** [comment]
Screenshot (112)

**Review by amantank — APPROVED** [review]

**Comment by karananu** [comment]
Thanks any other changes needed i have checked something is missing in
the website

**Comment by rolikaagarwal** [comment]
@karananu This is not looking good. Change it.

**Comment by karananu** [comment]
ok I will change it

**Pull request closed without merging**
