### PR TITLE
Construction and Planning 

### PR DESCRIPTION
**Pull request by rolikaagarwal**

### CODE REVIEW

**Comment by AbhiPatel10** [comment]
Please give Commit message more relevant to what you changed

**Comment by AbhiPatel10** [comment]
@rolikaagarwal do not close PR instead take Pull request and work on it. also i comment on your previous PR which you closed please work on it and push on your current PR

**Comment by rolikaagarwal** [comment]
I've made the changes.

**Comment by rolikaagarwal** [comment]
Height and width fixed.
image

**Comment by AbhiPatel10** [comment]
Looks good

**Comment by rolikaagarwal** [comment]
Added Padding and removed unwanted CSS.

**Comment by AbhiPatel10** [comment]
> Added Padding and removed unwanted CSS.

I asked you to replace padding with margin so remove margin and add padding.

**Comment by AbhiPatel10** [comment]
Yes good to go, please remember give meaningful comments while commit

**Comment by AbhiPatel10** [comment]
Also add close # pr id so it will automatically close Issue as well

**Pull request merged**
