### PR TITLE
animated back to top #468{video added}

### LINKED ISSUE #468: animated back to top button
the back to button will be animating linearly

### PR DESCRIPTION
**Pull request by harshita-2003**
## Summary
_Provide an overview of the change. List any dependencies that are required for this change._

## Type of change
_Please select the relevant option._
- [ ] Bug fix
- [ ] New feature
- [ ✔] Breaking change
- [ ] Documentation update
- [ ] Other (please describe)

## Checklist
_Please tick the relevant options._
- [✔ ] My code follows the code style of this project.
- [✔ ] My change requires a change to the documentation.
- [✔ ] I have updated the documentation accordingly.
- [✔ ] I have added tests to cover my changes.
- [✔ ] All new and existing tests passed.

## Screenshots
_Provide screenshots to help explain your changes._

https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/119532943/4f54f50a-32aa-4161-b6fc-1135134789fc

## Additional context
_Add any other context about the pull request here._

### CODE REVIEW

**Comment by Neilblaze** [comment]
The shown *bouncing effect* is **annoying**, but maybe we can optimize it to integrate it into the existing codebase. I think the bouncing effect can be added once the user scrolls to the end of the page. 

/cc: @kartikayasija thoughts?

**Comment by kartikayasija** [comment]
@Neilblaze I was thinking the same. It should only show when the user scrolls downward.

**Comment by Neilblaze** [comment]
@harshita-2003 you take the discussed [inputs](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/pull/473#issuecomment-1627321743) & make the changes accordingly.

**Comment by harshita-2003** [comment]
okay

**Pull request closed without merging**
