### PR TITLE
General info Section

### LINKED ISSUE #34: General info Section
image

### PR DESCRIPTION
**Pull request by kartikayasija**
closes #34 
image
image
image

### CODE REVIEW

**Comment by AbhiPatel10** [comment]
Looks good just resolve conflicts.

**Comment by kartikayasija** [comment]
Conflicts removed.

**Comment by AbhiPatel10** [comment]
Still not

**Comment by kartikayasija** [comment]
Conflicts resolved @AbhiPatel10

**Comment by AbhiPatel10** [comment]
Good to go.

**Pull request merged**
