### PR TITLE
Build with quality

### LINKED ISSUE #30: [Feature] : Build with quality materials
image

Find Similar Image and use it.

### PR DESCRIPTION
**Pull request by rolikaagarwal**
closes #30 
image

reduced size- 

image

mobile Screen - 

image

### CODE REVIEW

**Comment by rolikaagarwal** [comment]
@AbhiPatel10 please share some sample images. Unable to find similar images.

**Comment by AbhiPatel10** [comment]
Looks good but use whole width effectively and improve in responsive.

**Comment by AbhiPatel10** [comment]
Remove Box shadow and Update max width to 90%


resolve conflicts

**Comment by rolikaagarwal** [comment]
Box Shadow removed, max width updated and conflicts removed.

**Comment by AbhiPatel10** [comment]
Still need responsive between 1024 and 1151 px ----- reduce photo size in that screen

**Pull request merged**
