### PR TITLE
Added a transition to FAQ section.

### LINKED ISSUE #120: Improving the FAQ section
Adding transformation plus some other CSS additions.[GSSoC]

### PR DESCRIPTION
**Pull request by Anoushka-0410**
## Summary
Added a CSS transition to the 'answer' section of the FAQs (on-click).

## Type of change
_Please select the relevant option._
- [ ] Bug fix
- [&#9745; ] New feature
- [ ] Breaking change
- [ ] Documentation update
- [ ] Other (please describe)

## Checklist
_Please tick the relevant options._
- [&#9745; ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Screenshots
image

## Additional context
_Add any other context about the pull request here._

### CODE REVIEW

**Comment by kartikayasija** [comment]
Link the issue and also add screenshots in your PR

**Comment by Anoushka-0410** [comment]
Hi ! I've attached the screenshot. But I'm unable to link my issue. Could you please guide me through it?

**Comment by AbhiPatel10** [comment]
> Hi ! I've attached the screenshot. But I'm unable to link my issue. Could you please guide me through it?



> Hi ! I've attached the screenshot. But I'm unable to link my issue. Could you please guide me through it?

Add your Issue number Below Fixes #  like this( close#1 )

image

**Comment by Anoushka-0410** [comment]
Thank you so much!

**Comment by kartikayasija** [comment]
resolve conflicts.

**Comment by Anoushka-0410** [comment]
> resolve conflicts.

Done.

**Comment by kartikayasija** [comment]
@Anoushka-0410 not working, there is any syntax error in code.

**Comment by Anoushka-0410** [comment]
> @Anoushka-0410 not working, there is any syntax error in code.

The changes made were working in the forked repo but just saw that the previous PRs merged made similar changes to the repository. So my commits are not needed as someone already made the changes needed by my issue.

**Pull request closed without merging**
