### PR TITLE
Make the Slot Booking Page for the website

### LINKED ISSUE #4: Make the Slot Booking Page for the website

### PR DESCRIPTION
**Pull request by techRajat**
closes #4 
Technology used - HTML, CSS and JavaScript
Screenshot (151)
.............................................................................................................................................................................................................................................
Screenshot (152)
.............................................................................................................................................................................................................................................
Screenshot (153)
.............................................................................................................................................................................................................................................
Note: - This Slot Booking page also contains the navigation bar.

### CODE REVIEW

**Comment by AbhiPatel10** [comment]
Use all space effectively, take inspiration from below

https://www.freepik.com/free-psd/flat-design-medical-template-design_32255865.htm#query=registration%20form%20template&position=2&from_view=keyword&track=ais

https://www.jotform.com/form-templates/doctor-appointment-form

**Comment by techRajat** [comment]
@AbhiPatel10 Appointment page updated.
Screenshot (154)

**Comment by AbhiPatel10** [comment]
We should make some unique form, so can we make like this ? @techRajat 

https://goldengatecapital.netlify.app/register

**Comment by AbhiPatel10** [comment]
FormValidation.js page is not needed please add in script.js file. 

i tried it it's working fine.

**Comment by AbhiPatel10** [comment]
> > We should make some unique form, so can we make like this ? @techRajat
> > https://goldengatecapital.netlify.app/register
> 
> ok

Welcome Back

**Comment by techRajat** [comment]
@AbhiPatel10 bhaiya please have a look at the updated slot booking form.

**Comment by AbhiPatel10** [comment]
Looks good Just use all space effectively. like this

image

**Comment by techRajat** [comment]
> Looks good Just use all space effectively. like this
> 
> image

Done

**Comment by AbhiPatel10** [comment]
Looks good Connect with Navbar Button

**Comment by techRajat** [comment]
> Looks good Connect with Navbar Button

@AbhiPatel10  Done

**Pull request merged**
