### PR TITLE
Talkwithexpert

### PR DESCRIPTION
**Pull request by rolikaagarwal**

### CODE REVIEW

**Comment by rolikaagarwal** [comment]
issues fixed. 
closes #8
Full Screen- 
image

Mobile Screen- 
image
image

ONCLICK GET APPOINTMENT BUTTON 
image

**Comment by AbhiPatel10** [comment]
https://www.freepik.com/free-vector/flat-design-illustration-customer-support_12982910.htm#page=3&query=Contact%20With%20Our%20Experts&position=2&from_view=search&track=ais

Use this vector

remove the Get Appointment page; we will make a separate file later on. Also put your talkwithexpert.html code in the index.html file, and add CSS to style. css also use Class or ID to give CSS do not use html tag directly

**Comment by rolikaagarwal** [comment]
changes fixed

**Comment by AbhiPatel10** [comment]
image

Solve this problem and do not use light pink color, white color is good 👍

**Comment by rolikaagarwal** [comment]
issue fixed.

**Comment by AbhiPatel10** [comment]
Please resolve conflicts

**Comment by rolikaagarwal** [comment]
resolved

**Comment by AbhiPatel10** [comment]
Looks Good, Great work @rolikaagarwal , Go ahead and start working on other issues

**Pull request merged**
