### PR TITLE
animated back to top added #468 #473 {video attached}

### LINKED ISSUE #468: animated back to top button
the back to button will be animating linearly

### PR DESCRIPTION
**Pull request by harshita-2003**
## Summary
Back to top button added which starts animating only on hover , and it shows only when scrolled down 

## Fixes #468 

as you mentioned the points in #473 

## Type of change
_Please select the relevant option._
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change
- [ ] Documentation update
- [ ] Other (please describe)

## Checklist
_Please tick the relevant options._
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## Screenshots

https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/119532943/1c2cce9a-0786-4f65-8857-1b2c89342abb

## Additional context
_Add any other context about the pull request here._

### CODE REVIEW

**Comment by harshita-2003** [comment]
@Neilblaze  just want to confirm this task will be come under level 3 I believe as its about adding the functionality

**Comment by Neilblaze** [comment]
@harshita-2003 It won't be `level-3`, since I believe is not a custom feature that's being incorporated into the app. It's just minor CSS upgrade.

**Comment by harshita-2003** [comment]
Earlier it was not functional as not returning to top , I will accept anyway but would be glad it would be atleast level 2 😊

**Comment by Neilblaze** [comment]
> I will accept anyway but would be glad it would be atleast level 2

@harshita-2003 alright, I'll update the current with a `level-2` tag.

**Comment by Neilblaze** [comment]
Now, make the changes accordingly.

**Comment by harshita-2003** [comment]
Yes , it is completely functional now  i,e., it will return to top  and animates on hovering 
You can merge this PR.

**Comment by harshita-2003** [comment]
@Neilblaze can you look into this hovering effect of faq section , it matches with blue theme of the site

https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/119532943/61f78dd2-5d03-4b47-84ed-2f57ff0033c3

**Pull request closed without merging**
