### PR TITLE
[GSSOC'23] -  Styling and improving navbar

### PR DESCRIPTION
**Pull request by VyjayantiN**
## Summary
I made an exciting improvement to the navbar by adding the ability to highlight the current page. This means that when users navigate through the website, they will see a visual indicator that shows them exactly which page they are on. This small but impactful change greatly enhances the user experience and makes it easier for visitors to navigate and explore the site.

## Fixes # (issue)
Navbar is not highlighting the active tab due to which users may face difficulty to find which tab they are active on.

## Type of change
_Please select the relevant option._
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change
- [ ] Documentation update
- [ ] Other (please describe)

## Checklist
_Please tick the relevant options._
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Screenshots
_Provide screenshots to help explain your changes._
image

## Additional context
This improvement was inspired by user feedback. Users often find it challenging to keep track of their location within the website, especially when navigating through multiple pages. By adding the current page highlighting feature, I tried to provide a more intuitive and seamless browsing experience.

### CODE REVIEW

**Comment by kartikayasija** [comment]
Link the issue in your PR, Also give some margin between underline and navlink.

**Comment by VyjayantiN** [comment]
Okay I will

**Comment by VyjayantiN** [comment]
@kartikayasija I made necessary changes. Please check it out!! 
Please assign this under GSSOC'23.

**Comment by kartikayasija** [comment]
@VyjayantiN the underline is not looking good, just use the gradient color in the active class,, also give proper name to class like nav-active.

**Comment by piyushlakheda** [comment]
> @VyjayantiN the underline is not looking good, just use the gradient color in the active class,, also give proper name to class like nav-active.

Yes I would agree with this! Gradient would look more good!

**Comment by VyjayantiN** [comment]
> > @VyjayantiN the underline is not looking good, just use the gradient color in the active class,, also give proper name to class like nav-active.
> 
> Yes I would agree with this! Gradient would look more good!

Hey are you asking me to add gradient to the active nav tab or make the underline gradient?

**Pull request closed without merging**
