### PR TITLE
added new background image of service page

### PR DESCRIPTION
**Pull request by Anushkabh**
## Summary
Change the background image of service page

## Type of change
Updated the existing Image

## Screenshot
New one
Screenshot (5)
Old one
services2

### CODE REVIEW

**Comment by kartikayasija** [comment]
Also reduce the height,

**Comment by Anushkabh** [comment]
@kartikayasija  which image you are talking about? The one I uploaded?

**Comment by kartikayasija** [comment]
yes, just reduce the height of this section, make it like Repair section.

**Comment by Anushkabh** [comment]
@kartikayasija  i have reduced the height of image as told

**Pull request merged**
