### PR TITLE
Hire Us Section

### LINKED ISSUE #23: [Feature]: Make Hire us section
Screenshot from 2023-04-03 16-45-01

Take inspiration from https://goldengatecapital.netlify.app/

### PR DESCRIPTION
**Pull request by kartikayasija**
close #23 

image

### CODE REVIEW

**Comment by AbhiPatel10** [comment]
It will look like this 

give padding in footer top

Give (#cccccc) color to footer background

image

**Comment by kartikayasija** [comment]
Changes Done

**Comment by AbhiPatel10** [comment]
Resolve conflicts

**Comment by kartikayasija** [comment]
Conflicts Resolved

**Comment by AbhiPatel10** [comment]
Great, Good to go

**Pull request merged**
