### PR TITLE
Updated the Readme file

### PR DESCRIPTION
**Pull request by prernadabi23**
fixes: #6 
Made changes in the Readme file and have given a glimpse of the website of what it is used for.

### CODE REVIEW

**Comment by prernadabi23** [comment]
Hello, @AbhiPatel10 If you would like some changes I can revise it.

**Comment by kartikayasija** [comment]
@prernadabi23 Please complete the Project Initialization for backend. Also remove the screenshot.

**Comment by prernadabi23** [comment]
@kartikayasija Sure! Do you also want me to add contributing guidelines in more detail? For example:

# Steps to contribute to this repository:

1. Find the issue you want to work on or can make a new one by tapping on `new issue`.
2. You will get assigned an issue by the mentor.
3. Fork the repo.
4. Make sure your fork is up to date with the changes. `sync fork`.
5. Clone the repository in your laptop.    `git clone https://github.com/<your-username>/AISKCON-CONSTRUCTION.git`
6. Make a new branch for your changes.  `git branch <nameofthebranch>`   `git checkout <nameofthebranch>`
7. Make the required changes then:  `git add .`  
8. Make the commit message appropriate explaining the changes `git commit -m "<chnages>"`
9. Push the changes from your new branch `git push -u origin "nameofthebranch"`
10. You will see the `compare and pull request` button on your forked repository.
11. Explain the changes you have done and then you're good to go.
12. yay! you have made a contribution to the repository.



And for the project initialization:

For Front-End:

open `index.html` and start the server

For Back-End:
Run this cmd in terminal

`npm run dev`

**Comment by kartikayasija** [comment]
@prernadabi23 No need for Contribution guidelines, just project initialization is fine.
make it
 `cd backend`
`node app.js`

**Comment by prernadabi23** [comment]
okay.

**Comment by prernadabi23** [comment]
I have made the changes. You can check.
@kartikayasija

**Pull request merged**
